import { Container } from "@material-ui/core";
import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";
import CustomizedSnackbars from "../components/Snackbar";

const MainLayout = ({ children, title }) => {
  return (
    <>
      <CustomizedSnackbars />
      <Head>
        <title>{title || "Trainer"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <Container className="min-vh-100">
        <Header />
        <div>{children}</div>
      </Container>
      <Footer />
    </>
  );
};

export default MainLayout;
